# Generated by Django 5.1.4 on 2025-02-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('subjects', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=255)),
                ('first_published', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'works',
                'managed': False,
            },
        ),
    ]
