# Generated by Django 5.1.4 on 2025-02-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_work_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='work',
            table='works',
        ),
    ]
