# Generated by Django 4.2.19 on 2025-03-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userbooklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('subjects', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=255)),
                ('cover', models.IntegerField(blank=True, null=True)),
                ('first_published', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
