# Generated by Django 5.1.4 on 2025-04-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userbooklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={},
        ),
    ]
