# Generated by Django 4.2.19 on 2025-04-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='top_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
