# Generated by Django 4.2.19 on 2025-04-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='key',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
