# Generated by Django 4.2.19 on 2025-04-25 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0009_alter_author_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedBooks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('cover', models.IntegerField(blank=True, null=True)),
                ('first_published', models.IntegerField(blank=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
