# Generated by Django 4.2.19

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_recommendedbooks'),  # Make sure this matches your last migration
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendedBooks',
        ),
    ]