# Generated by Django 4.2.19 on 2025-04-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_delete_work_review_user'),
        ('myapp', '0012_remove_recommendedbooks'),
    ]

    operations = [
    ]
